# Generated by Django 2.1.3 on 2018-11-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0005_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='failure_limit',
            field=models.PositiveIntegerField(default=3, verbose_name='Maximum number of failed logins'),
        ),
    ]
