# Generated by Django 2.1.3 on 2018-11-28 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0007_auto_20181128_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='cooloff_time',
        ),
    ]
